### PR TITLE
Get limits from MDB dicitionary load instead of parameter archive

### LINKED ISSUE #190: Limits should be fetched from the mdb and not the parameter archive
**Is your feature request related to a problem? Please describe.**
The Open MCT-Yamcs limit provider currently fetches limit definitions from the parameter archive. This has a couple of downsides:
1. We will not be able to render limit lines for parameters with no values yet. This would require the user to reload a plot once values have been received
2. Requests to the parameter archive are expensive

Additionally, limit information should be cached to avoid having to make an extra request to the server for limit information every time we want to render limits in a plot.

**Describe the solution you'd like**
Static limit information is provided [by the MDB API](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/) which is already used for fetching the dictionary. So, it could be fetched once [when the dictionary is loaded](https://github.com/akhenry/openmct-yamcs/blob/fab4d5677ee92927a9b070184007fa7824a60019/src/providers/object-provider.js#L188) and cached in memory [with other telemetry metadata](https://github.com/akhenry/openmct-yamcs/blob/fab4d5677ee92927a9b070184007fa7824a60019/src/providers/object-provider.js#L327).

### PR DESCRIPTION
**Pull request by scottbell**
Closes #190 

### Describe your changes:
When we're loading the telemetry dictionary, we cache the limits for the telemetry object, and then use these cached limits later in the limit provider. This allows us to skip looking into the parameter archive for limit information.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
Limits working with YAMCS:
Screen Shot 2022-10-17 at 3 16 25 PM

**Comment by scottbell** [comment]
Unfortunately YAMCS doesn't really have any alarms in its quickstart, so we'll have to do some manual testing on this one for the inteirm. Check ticket for how to do this.

**Review by ozyx — CHANGES_REQUESTED** [review]
The code all looks good, and there are some really great improvements here. The e2e test works well, and I even copied and tested it against `master` and it fails as expected so the number of network requests are indeed decreased.

I found one (big?) issue while testing (following testing instructions provided in the linked issue). After dragging "Latitude" into my newly created Overlay Plot, telemetry is displayed correctly (along with limit lines and alarm markers). But if I refresh the page, the Overlay Plot no longer shows plotted data. This persists unless I remove the telemetry object from the plot and add it again.

Is there some change that needs to be made on the OpenMCT side?

**Comment by scottbell** [comment]
> The code all looks good, and there are some really great improvements here. The e2e test works well, and I even copied and tested it against `master` and it fails as expected so the number of network requests are indeed decreased.
> 
> I found one (big?) issue while testing (following testing instructions provided in the linked issue). After dragging "Latitude" into my newly created Overlay Plot, telemetry is displayed correctly (along with limit lines and alarm markers). But if I refresh the page, the Overlay Plot no longer shows plotted data. This persists unless I remove the telemetry object from the plot and add it again.
> 
> image
> 
> Is there some change that needs to be made on the OpenMCT side?

@ozyx There shouldn't be! I'll take a look.

**Comment by scottbell** [comment]
It appears to be a race condition in plots. Adding a 100ms delay (as if we were still fetching from the parameter archive) resolves the issue:
```
    getLimits(domainObject) {
        const limits = domainObject.configuration.limits;

        return {
            // eslint-disable-next-line require-await
            limits: async function () {
                await new Promise(resolve => setTimeout(resolve, 100));

                return limits;
            }
        };
    }
}
```

I'll see we can fix this in Plots. Note, I wasn't able to get this working in `master` either without the following change:
```
async getLimitsForParameter(id, fullId) {
        let url = `${this.url}api/archive/${this.instance}`;
        url += '/parameters' + idToQualifiedName(id);
        url += '?limit=1&order=desc';

        const res = await fetch(encodeURI(url));
        const results = await res.json();

        return this.convertToLimits(id, results);
    }
```

**Comment by scottbell** [comment]
@ozyx I've got another [PR to address the timing issue in plots](https://github.com/nasa/openmct/pull/5896). Hopefully that solves that!

**Comment by ozyx** [comment]
> @ozyx I've got another [PR to address the timing issue in plots](https://github.com/nasa/openmct/pull/5896). Hopefully that solves that!

Tested with this PR branch and it seems to have resolved the issue!

**Review by ozyx — APPROVED** [review]

**Pull request merged**
