### PR TITLE
New default display and related functionality

### PR DESCRIPTION
**Pull request by charlesh88**
### Describe your changes:
- Example Flexible Layout display loads by default at application start.
- Illustrates multiple examples of Open MCT views including conditionals, conditional styling, Gauges, LAD Tables, Tab views and nested layouts.
~~- Updated README to include note about alternate build command, a workaround as noted in #427.~~

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by charlesh88** [comment]
### Testing Notes
No original issue for this (?) so testing notes here.
1. Follow [all steps](https://github.com/akhenry/openmct-yamcs/blob/master/README.md) to setup the openmct-yamcs plugin, including setting up the [yamcs-quickstart](https://github.com/yamcs/quickstart) project.
2. Run both projects in terminal.
3. Go to the URL for openmct-yamcs: by default, http://localhost:9000.
4. Verify that Open MCT loads without console errors. The Time Conductor should be Real-time and using normal default values.
6. Verify that the default display is shown. Click through the Tabs view in the display and verify that screens appear as shown in the reference section below.

### Reference
Screenshot 2024-09-11 at 10 13 17 AM
Screenshot 2024-09-11 at 10 13 26 AM
Screenshot 2024-09-11 at 10 13 36 AM
Screenshot 2024-09-11 at 10 13 43 AM

**Comment by davetsay** [comment]
@jvigliotta to write a test. @akhenry ready for review

**Comment by akhenry** [comment]
@unlikelyzero To describe tests needed here
@jvigliotta  To remove comment about npm build and master.

**Comment by unlikelyzero** [comment]
We need tests:

- Verify display is loaded without console errors 
- Verify display components are visible

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
