### PR TITLE
Query for aggregate members for search results

### LINKED ISSUE #184: Search isn't working for aggregate parameters
#### Summary
Searching in OpenMCT for telemetry/parameters doesn't work for children of aggregate parameters.

#### Expected vs Current Behavior
Children of aggregate parameters should return that match the search query.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Search for a child of an aggregate parameter in OpenMCT
2. Notice no results

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Additional Information
Initial investigation by @akhenry revealed it's due to some additional query parameters we need to add to the [YAMCS telemetry query](https://docs.yamcs.org/yamcs-http-api/mdb/list-parameters/), specifically `searchMembers` should be `true` and `details` should be `false`.

### PR DESCRIPTION
**Pull request by scottbell**
Closes #184 

### Describe your changes:
Check members to see if query matches as well. Also refactored plugin to use OpenMCT's lint rules and did some general refactoring.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
@akhenry One open question I have - does YAMCS flatten nested members for us? Namely, if an aggregated parameter has a member 5 levels deep that matches the query, does the search result from the YAMCS query come in the top result `member` field? I'm thinking it does, but would like to validate. Unfortunately the quickstart-yamcs XTCE doesn't have a nested aggregated parameter. I'm going to see if I can add a nested aggregated type to quickstart XTCE.

**Comment by scottbell** [comment]
> @akhenry One open question I have - does YAMCS flatten nested members for us? Namely, if an aggregated parameter has a member 5 levels deep that matches the query, does the search result from the YAMCS query come in the top result `member` field? I'm thinking it does, but would like to validate. Unfortunately the quickstart-yamcs XTCE doesn't have a nested aggregated parameter. I'm going to see if I can add a nested aggregated type to quickstart XTCE.

@akhenry I tested with this XTCE and searched for "Child". It seems to find deeply nested members now. It's zipped because Github won't let me attach XML 🤷‍♂️
[xtce.xml.zip](https://github.com/akhenry/openmct-yamcs/files/9633660/xtce.xml.zip)

**Comment by akhenry** [comment]
> @akhenry One open question I have - does YAMCS flatten nested members for us? Namely, if an aggregated parameter has a member 5 levels deep that matches the query, does the search result from the YAMCS query come in the top result `member` field? I'm thinking it does, but would like to validate. Unfortunately the quickstart-yamcs XTCE doesn't have a nested aggregated parameter. I'm going to see if I can add a nested aggregated type to quickstart XTCE.

Sorry, I don't know the answer to this off the top of my head, but it looks like you've confirmed it yourself.

**Comment by scottbell** [comment]
> > @akhenry One open question I have - does YAMCS flatten nested members for us? Namely, if an aggregated parameter has a member 5 levels deep that matches the query, does the search result from the YAMCS query come in the top result `member` field? I'm thinking it does, but would like to validate. Unfortunately the quickstart-yamcs XTCE doesn't have a nested aggregated parameter. I'm going to see if I can add a nested aggregated type to quickstart XTCE.
> 
> Sorry, I don't know the answer to this off the top of my head, but it looks like you've confirmed it yourself.

It does not!

**Pull request merged**
